service: boilerplate-api

frameworkVersion: "3"

useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs18.x
  lambdaHashingVersion: "20201221"
  timeout: 30

functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /hello
          method: get
          #authorizer:
          #  name: cognitoAuthorizer
          #  arn: ${env:boilerplate_COGNITO_ARN}
          cors: true
  rpc:
    handler: src/rpcHandler.handler
    events:
      - http:
          path: /rpc
          method: post
          #authorizer:
          #  name: cognitoAuthorizer
          #  arn: ${env:boilerplate_COGNITO_ARN}
          cors: true
